#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   https://www.apache.org/licenses/LICENSE-2.0

# ---- DO NOT EDIT THIS FILE ----
# This is the standard Gradle wrapper script.

set -e

# Resolve symlinks: this works both on Linux/macOS and on Windows (Git Bash)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GRADLE_WRAPPER_JAR="$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar"

# If the wrapper JAR is missing, pull it from the official Gradle distribution
if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
  echo "Wrapper JAR not found – downloading..."
  curl -L -o "$GRADLE_WRAPPER_JAR" https://services.gradle.org/distributions/gradle-8.11-bin.zip \
    && unzip -q -o "$GRADLE_WRAPPER_JAR" -d "$(dirname "$GRADLE_WRAPPER_JAR")"
fi

exec "$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar" "$@"
